# Generated by Django 2.2.4 on 2019-12-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('prefijo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Contrasenas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('contrasena', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dir', to='generador.Direcciones')),
            ],
            options={
                'verbose_name': 'Contraseña',
                'verbose_name_plural': 'Contraseñas',
            },
        ),
    ]
