# Generated by Django 2.2.4 on 2019-12-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrasenas',
            name='hecho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrasenas',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrasenas',
            name='contrasena',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Contraseña'),
        ),
    ]
